version: '2.1'
services:
  datos:
    build: .
    links:
      - influxdb
    depends_on:
      - influxdb
  influxdb:
      image: influxdb
      ports:
        - "8083:8083"
        - "8086:8086"
        - "8090:8090"
      healthcheck:
        test: ["CMD", "ping", "-c","1", "http://localhost:8086"]
        interval: 30s
        timeout: 10s
        retries: 5
